# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160425_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_reply',
            name='trigger',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
