# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 23:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_question_reply_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_answer',
            name='episode',
        ),
        migrations.AddField(
            model_name='user_answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_answer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 25, 23, 55, 13, 792464, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
